spring:
  application:
    name: account-consumer-reactive
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/account
    password: tx135!@#$
    username: transaction-manager
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
  file:
    name: application.log
otel:
  trace:
    endpoint: http://localhost:4318/v1/traces